name: Lambda CI

on:
  pull_request:
    branches:
      - main

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Compile Python
        run: |
          python -m py_compile lambda/lambda_function.py

      - name: Package Lambda
        run: |
          cd lambda
          zip function.zip lambda_function.py
