name: Deploy Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Package Lambda
        run: |
          cd lambda
          zip function.zip lambda_function.py

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name image-moderation-processor \
            --zip-file fileb://lambda/function.zip
